sudo: false
language: node_js

matrix:
  include:
  - node_js: 4
  - node_js: 6
  - node_js: stable
    env: SAUCE=true

# Make sure we have new NPM.
before_install:
  - npm install -g npm

script:
  - npm run lint
  - npm test
  - npm run coverage

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm run coverage-publish

env:
  - CXX=g++-4.8

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
